version: "3.4"

services:
  php:
    image: thecodingmachine/php:7.4-v4-fpm-node18
    container_name: ${PROJECT_NAME}-php
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:rw,cached
    environment:
      APP_ENV: "${APP_ENV}"
      PHP_IDE_CONFIG: "serverName=${PROJECT_NAME}"
      DATABASE_URL: "postgres://${DB_USER:-app_user}:${DB_PWD:-app_password}@${PROJECT_NAME:-kijireader}-db:5432/${DB_NAME:-kijireader}?sslmode=disable&charset=utf8"
      PHP_EXTENSIONS: "pdo_pgsql pgsql pdo_sqlite sqlite3 gd intl xdebug"
      PHP_INI_MEMORY_LIMIT: -1
      PHP_INI_XDEBUG__MODE: "debug"
      PHP_INI_XDEBUG__CLIENT_PORT: 9003
      PHP_INI_XDEBUG__IDEKEY: "PHPSTORM"
      PHP_EXTENSION_XDEBUG: 1

  caddy:
    image: caddy
    container_name: "${PROJECT_NAME}-caddy"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      PROJECT_HOST: ${PROJECT_HOST}
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 443
        protocol: udp
    restart: unless-stopped

  db:
    image: postgres
    container_name: "${PROJECT_NAME}-db"
    environment:
      POSTGRES_DB: ${DB_NAME:-kijireader}
      POSTGRES_USER: ${DB_USER:-app_user}
      POSTGRES_PASSWORD: ${DB_PWD:-app_password}
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    restart: unless-stopped

volumes:
  db_data:
  caddy_data:
  caddy_config: